universe            = vanilla
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
RequestCpus = 4
output = ../condor_logs/job_$(Cluster)_$(Process).out
error  = ../condor_logs/job_$(Cluster)_$(Process).err
log    = ../condor_logs/job_$(Cluster).log
+JobFlavour = "microcentury"

# Set executable for the first set
executable = runJob_MC.sh

arguments = DisplacedMu-Pt-2To10 DisplacedMu-Pt-2To10.root
queue 1
arguments = DisplacedMu-Pt-10To30 DisplacedMu-Pt-10To30.root
queue 1
arguments = DisplacedMu-Pt-30To100 DisplacedMu-Pt-30To100.root
queue 1
# Now change the executable for the Cosmics job
# executable = runJob_cosmics.sh
# queue 1
